### ISSUE TITLE
stopped working with RN24

### ISSUE THREAD

**Issue by faceyspacey** [skevy/babel-preset-react-native-stage-0#1]
I've done the suggestions in the readme, e.g. resetting the cache. This used to work beautifully, but now not all, and of course my app doesn't work.

**Comment by faceyspacey** [comment]
well, i did it a few more times, i.e. watchman-del-all, etc. And started using the packager directly, rather than when xcode starts it up, and it started working.

**Comment by skevy** [comment]
I'm using it successfully on RN-24...i'm not aware of anything that would prevent this from working (as nothing drastic has changed in that release re: packager).

If you keep encountering problems let me know, and I'll reopen the ticket.
