### ISSUE TITLE
Does not work for the "for of" statements

### ISSUE THREAD

**Issue by afilp** [skevy/babel-preset-react-native-stage-0#3]
I did what is recommended here (thank you by the way), but it does not seem to work for the ES2015 "for of" iterators.

This is what I did:

![image](https://cloud.githubusercontent.com/assets/7850073/17271690/12015208-568b-11e6-9f7e-bac79fc4c3eb.png)

Then:

![image](https://cloud.githubusercontent.com/assets/7850073/17271695/20a6a2ae-568b-11e6-9bed-de4dca880268.png)

Still, the app throws error when it reaches the "for of" iterator construct (ES2015 feature).

Any ideas what we could do?

Thanks!

**Comment by afilp** [comment]
@skevy Do you have any resolution on this please? I had to use the entire _babel polyfill_ just for that.

**Comment by skevy** [comment]
Hi @af7 -

This is left out on purpose, unfortunately. Symbol polyfills tend to be pretty unreliable...so I didn't include the polyfill here. Using babel-polyfill, or some specific symbol polyfill, is the right solution for the time being.

**Comment by afilp** [comment]
@skevy Thanks. It has been a pain and I believe that React Native should provide a solution inherently. "For Of" is very common nowadays.
